import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/home/Navbar";
import Providers from "@/components/Providers";
import Footer from "@/components/home/Footer";
import MobileNavbar from "@/components/home/MobileNavbar";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "max-w-[120rem] mx-auto md:p-8 p-4")}
      >
        <Providers>
          <Navbar />
          <MobileNavbar />
          <div className="mt-20">{children}</div>
          <Analytics />
        </Providers>
      </body>
      <Footer />
    </html>
  );
}
